# CMake generated Testfile for 
# Source directory: /home/chx/full-vesion/zk_math/test
# Build directory: /home/chx/full-vesion/zk_math/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(arith_Mys_exp_exact "./run" "/home/chx/full-vesion/zk_math/bin/test_arith_Mys_exp_exact")
set_tests_properties(arith_Mys_exp_exact PROPERTIES  WORKING_DIRECTORY "/home/chx/full-vesion/zk_math/" _BACKTRACE_TRIPLES "/home/chx/full-vesion/zk_math/test/CMakeLists.txt;14;add_test;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;19;add_test_case_with_run;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;0;")
add_test(arith_Mys_div "./run" "/home/chx/full-vesion/zk_math/bin/test_arith_Mys_div")
set_tests_properties(arith_Mys_div PROPERTIES  WORKING_DIRECTORY "/home/chx/full-vesion/zk_math/" _BACKTRACE_TRIPLES "/home/chx/full-vesion/zk_math/test/CMakeLists.txt;14;add_test;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;20;add_test_case_with_run;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;0;")
add_test(arith_Mys_rsqrt "./run" "/home/chx/full-vesion/zk_math/bin/test_arith_Mys_rsqrt")
set_tests_properties(arith_Mys_rsqrt PROPERTIES  WORKING_DIRECTORY "/home/chx/full-vesion/zk_math/" _BACKTRACE_TRIPLES "/home/chx/full-vesion/zk_math/test/CMakeLists.txt;14;add_test;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;21;add_test_case_with_run;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;0;")
add_test(arith_Mys_softmax "./run" "/home/chx/full-vesion/zk_math/bin/test_arith_Mys_softmax")
set_tests_properties(arith_Mys_softmax PROPERTIES  WORKING_DIRECTORY "/home/chx/full-vesion/zk_math/" _BACKTRACE_TRIPLES "/home/chx/full-vesion/zk_math/test/CMakeLists.txt;14;add_test;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;22;add_test_case_with_run;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;0;")
add_test(arith_Mys_truncation "./run" "/home/chx/full-vesion/zk_math/bin/test_arith_Mys_truncation")
set_tests_properties(arith_Mys_truncation PROPERTIES  WORKING_DIRECTORY "/home/chx/full-vesion/zk_math/" _BACKTRACE_TRIPLES "/home/chx/full-vesion/zk_math/test/CMakeLists.txt;14;add_test;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;23;add_test_case_with_run;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;0;")
add_test(arith_Mys_relu "./run" "/home/chx/full-vesion/zk_math/bin/test_arith_Mys_relu")
set_tests_properties(arith_Mys_relu PROPERTIES  WORKING_DIRECTORY "/home/chx/full-vesion/zk_math/" _BACKTRACE_TRIPLES "/home/chx/full-vesion/zk_math/test/CMakeLists.txt;14;add_test;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;24;add_test_case_with_run;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;0;")
add_test(arith_Mys_layernorm "./run" "/home/chx/full-vesion/zk_math/bin/test_arith_Mys_layernorm")
set_tests_properties(arith_Mys_layernorm PROPERTIES  WORKING_DIRECTORY "/home/chx/full-vesion/zk_math/" _BACKTRACE_TRIPLES "/home/chx/full-vesion/zk_math/test/CMakeLists.txt;14;add_test;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;25;add_test_case_with_run;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;0;")
add_test(arith_Mys_gelu "./run" "/home/chx/full-vesion/zk_math/bin/test_arith_Mys_gelu")
set_tests_properties(arith_Mys_gelu PROPERTIES  WORKING_DIRECTORY "/home/chx/full-vesion/zk_math/" _BACKTRACE_TRIPLES "/home/chx/full-vesion/zk_math/test/CMakeLists.txt;14;add_test;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;26;add_test_case_with_run;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;0;")
add_test(arith_Mys_maxpool "./run" "/home/chx/full-vesion/zk_math/bin/test_arith_Mys_maxpool")
set_tests_properties(arith_Mys_maxpool PROPERTIES  WORKING_DIRECTORY "/home/chx/full-vesion/zk_math/" _BACKTRACE_TRIPLES "/home/chx/full-vesion/zk_math/test/CMakeLists.txt;14;add_test;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;27;add_test_case_with_run;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;0;")
add_test(arith_Mys_sigmoid "./run" "/home/chx/full-vesion/zk_math/bin/test_arith_Mys_sigmoid")
set_tests_properties(arith_Mys_sigmoid PROPERTIES  WORKING_DIRECTORY "/home/chx/full-vesion/zk_math/" _BACKTRACE_TRIPLES "/home/chx/full-vesion/zk_math/test/CMakeLists.txt;14;add_test;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;28;add_test_case_with_run;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;0;")
add_test(math_LUT "./run" "/home/chx/full-vesion/zk_math/bin/test_math_LUT")
set_tests_properties(math_LUT PROPERTIES  WORKING_DIRECTORY "/home/chx/full-vesion/zk_math/" _BACKTRACE_TRIPLES "/home/chx/full-vesion/zk_math/test/CMakeLists.txt;14;add_test;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;31;add_test_case_with_run;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;0;")
add_test(math_LUTRange "./run" "/home/chx/full-vesion/zk_math/bin/test_math_LUTRange")
set_tests_properties(math_LUTRange PROPERTIES  WORKING_DIRECTORY "/home/chx/full-vesion/zk_math/" _BACKTRACE_TRIPLES "/home/chx/full-vesion/zk_math/test/CMakeLists.txt;14;add_test;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;32;add_test_case_with_run;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;0;")
add_test(math_positiveDigDecAny "./run" "/home/chx/full-vesion/zk_math/bin/test_math_positiveDigDecAny")
set_tests_properties(math_positiveDigDecAny PROPERTIES  WORKING_DIRECTORY "/home/chx/full-vesion/zk_math/" _BACKTRACE_TRIPLES "/home/chx/full-vesion/zk_math/test/CMakeLists.txt;14;add_test;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;33;add_test_case_with_run;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;0;")
add_test(math_positiveTruncation "./run" "/home/chx/full-vesion/zk_math/bin/test_math_positiveTruncation")
set_tests_properties(math_positiveTruncation PROPERTIES  WORKING_DIRECTORY "/home/chx/full-vesion/zk_math/" _BACKTRACE_TRIPLES "/home/chx/full-vesion/zk_math/test/CMakeLists.txt;14;add_test;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;34;add_test_case_with_run;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;0;")
add_test(math_generalTruncation "./run" "/home/chx/full-vesion/zk_math/bin/test_math_generalTruncation")
set_tests_properties(math_generalTruncation PROPERTIES  WORKING_DIRECTORY "/home/chx/full-vesion/zk_math/" _BACKTRACE_TRIPLES "/home/chx/full-vesion/zk_math/test/CMakeLists.txt;14;add_test;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;35;add_test_case_with_run;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;0;")
add_test(math_max "./run" "/home/chx/full-vesion/zk_math/bin/test_math_max")
set_tests_properties(math_max PROPERTIES  WORKING_DIRECTORY "/home/chx/full-vesion/zk_math/" _BACKTRACE_TRIPLES "/home/chx/full-vesion/zk_math/test/CMakeLists.txt;14;add_test;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;36;add_test_case_with_run;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;0;")
add_test(math_msnzb "./run" "/home/chx/full-vesion/zk_math/bin/test_math_msnzb")
set_tests_properties(math_msnzb PROPERTIES  WORKING_DIRECTORY "/home/chx/full-vesion/zk_math/" _BACKTRACE_TRIPLES "/home/chx/full-vesion/zk_math/test/CMakeLists.txt;14;add_test;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;37;add_test_case_with_run;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;0;")
add_test(math_extend "./run" "/home/chx/full-vesion/zk_math/bin/test_math_extend")
set_tests_properties(math_extend PROPERTIES  WORKING_DIRECTORY "/home/chx/full-vesion/zk_math/" _BACKTRACE_TRIPLES "/home/chx/full-vesion/zk_math/test/CMakeLists.txt;14;add_test;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;38;add_test_case_with_run;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;0;")
add_test(math_exp "./run" "/home/chx/full-vesion/zk_math/bin/test_math_exp")
set_tests_properties(math_exp PROPERTIES  WORKING_DIRECTORY "/home/chx/full-vesion/zk_math/" _BACKTRACE_TRIPLES "/home/chx/full-vesion/zk_math/test/CMakeLists.txt;14;add_test;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;39;add_test_case_with_run;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;0;")
add_test(math_div "./run" "/home/chx/full-vesion/zk_math/bin/test_math_div")
set_tests_properties(math_div PROPERTIES  WORKING_DIRECTORY "/home/chx/full-vesion/zk_math/" _BACKTRACE_TRIPLES "/home/chx/full-vesion/zk_math/test/CMakeLists.txt;14;add_test;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;40;add_test_case_with_run;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;0;")
add_test(math_rsqrt "./run" "/home/chx/full-vesion/zk_math/bin/test_math_rsqrt")
set_tests_properties(math_rsqrt PROPERTIES  WORKING_DIRECTORY "/home/chx/full-vesion/zk_math/" _BACKTRACE_TRIPLES "/home/chx/full-vesion/zk_math/test/CMakeLists.txt;14;add_test;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;41;add_test_case_with_run;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;0;")
add_test(math_softmax "./run" "/home/chx/full-vesion/zk_math/bin/test_math_softmax")
set_tests_properties(math_softmax PROPERTIES  WORKING_DIRECTORY "/home/chx/full-vesion/zk_math/" _BACKTRACE_TRIPLES "/home/chx/full-vesion/zk_math/test/CMakeLists.txt;14;add_test;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;42;add_test_case_with_run;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;0;")
add_test(math_layernorm "./run" "/home/chx/full-vesion/zk_math/bin/test_math_layernorm")
set_tests_properties(math_layernorm PROPERTIES  WORKING_DIRECTORY "/home/chx/full-vesion/zk_math/" _BACKTRACE_TRIPLES "/home/chx/full-vesion/zk_math/test/CMakeLists.txt;14;add_test;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;43;add_test_case_with_run;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;0;")
add_test(math_cmpRealVrfyPositive "./run" "/home/chx/full-vesion/zk_math/bin/test_math_cmpRealVrfyPositive")
set_tests_properties(math_cmpRealVrfyPositive PROPERTIES  WORKING_DIRECTORY "/home/chx/full-vesion/zk_math/" _BACKTRACE_TRIPLES "/home/chx/full-vesion/zk_math/test/CMakeLists.txt;14;add_test;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;44;add_test_case_with_run;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;0;")
add_test(math_cmpRealVrfyP "./run" "/home/chx/full-vesion/zk_math/bin/test_math_cmpRealVrfyP")
set_tests_properties(math_cmpRealVrfyP PROPERTIES  WORKING_DIRECTORY "/home/chx/full-vesion/zk_math/" _BACKTRACE_TRIPLES "/home/chx/full-vesion/zk_math/test/CMakeLists.txt;14;add_test;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;45;add_test_case_with_run;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;0;")
add_test(math_cmpRealPositive "./run" "/home/chx/full-vesion/zk_math/bin/test_math_cmpRealPositive")
set_tests_properties(math_cmpRealPositive PROPERTIES  WORKING_DIRECTORY "/home/chx/full-vesion/zk_math/" _BACKTRACE_TRIPLES "/home/chx/full-vesion/zk_math/test/CMakeLists.txt;14;add_test;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;46;add_test_case_with_run;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;0;")
add_test(math_relu "./run" "/home/chx/full-vesion/zk_math/bin/test_math_relu")
set_tests_properties(math_relu PROPERTIES  WORKING_DIRECTORY "/home/chx/full-vesion/zk_math/" _BACKTRACE_TRIPLES "/home/chx/full-vesion/zk_math/test/CMakeLists.txt;14;add_test;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;47;add_test_case_with_run;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;0;")
add_test(math_gelu "./run" "/home/chx/full-vesion/zk_math/bin/test_math_gelu")
set_tests_properties(math_gelu PROPERTIES  WORKING_DIRECTORY "/home/chx/full-vesion/zk_math/" _BACKTRACE_TRIPLES "/home/chx/full-vesion/zk_math/test/CMakeLists.txt;14;add_test;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;48;add_test_case_with_run;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;0;")
add_test(math_sigmoid "./run" "/home/chx/full-vesion/zk_math/bin/test_math_sigmoid")
set_tests_properties(math_sigmoid PROPERTIES  WORKING_DIRECTORY "/home/chx/full-vesion/zk_math/" _BACKTRACE_TRIPLES "/home/chx/full-vesion/zk_math/test/CMakeLists.txt;14;add_test;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;49;add_test_case_with_run;/home/chx/full-vesion/zk_math/test/CMakeLists.txt;0;")
